/*
 *     Copyright (C) 2026 Gab Nikumura
 *
 *     Nanoid is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 */

import 'package:nanoid/main.dart' show logger;
import 'package:nanoid/models/lyrics.dart';
import 'package:nanoid/services/proxy_manager.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

/// Last-resort synced lyrics built from a video's YouTube caption track.
///
/// Captions are not guaranteed to be official lyrics, so this source is only
/// used after dedicated lyrics providers fail. Keeping it as a distinct source
/// also lets the player tell listeners exactly where the words came from.
class YouTubeTranscriptService {
  factory YouTubeTranscriptService() => _instance;
  YouTubeTranscriptService._();

  static final YouTubeTranscriptService _instance =
      YouTubeTranscriptService._();

  static const _timeout = Duration(seconds: 10);

  Future<Lyrics?> fetch(
    String videoId, {
    String preferredLanguage = 'en',
  }) async {
    final id = videoId.trim();
    if (id.isEmpty) return null;

    try {
      final captionsClient = ProxyManager()
          .getClientSync()
          .videos
          .closedCaptions;
      final manifest = await captionsClient.getManifest(id).timeout(_timeout);
      if (manifest.tracks.isEmpty) return null;

      final trackInfo = _pickTrack(manifest, preferredLanguage);
      final track = await captionsClient.get(trackInfo).timeout(_timeout);
      if (track.captions.isEmpty) return null;

      final buffer = StringBuffer('[by:YouTube transcript]\n');
      String? previousText;
      for (final caption in track.captions) {
        final text = caption.text
            .replaceAll(RegExp('<[^>]+>'), '')
            .replaceAll(RegExp(r'\s+'), ' ')
            .trim();
        if (text.isEmpty || text == previousText) continue;
        previousText = text;
        buffer
          ..write(_timestamp(caption.offset))
          ..writeln(text);
      }

      final lrc = buffer.toString().trim();
      if (!lrc.contains(RegExp(r'\[\d{2,}:\d{2}\.\d{2}\]'))) return null;
      return Lyrics.synced(lrc, source: 'YouTube transcript');
    } catch (error, stackTrace) {
      logger.log(
        'YouTube transcript lookup failed for $id',
        error: error,
        stackTrace: stackTrace,
      );
      return null;
    }
  }

  ClosedCaptionTrackInfo _pickTrack(
    ClosedCaptionManifest manifest,
    String preferredLanguage,
  ) {
    final preferred = preferredLanguage.toLowerCase().split('-').first;
    final tracks = manifest.tracks.toList();

    int score(ClosedCaptionTrackInfo track) {
      var result = 0;
      final language = track.language.code.toLowerCase();
      if (language == preferred) {
        result += 100;
      } else if (language.split('-').first == preferred) {
        result += 80;
      } else if (language.startsWith('en')) {
        result += 40;
      }
      if (!track.isAutoGenerated) result += 20;
      if (track.format == ClosedCaptionFormat.srv1) result += 5;
      return result;
    }

    tracks.sort((a, b) => score(b).compareTo(score(a)));
    return tracks.first;
  }

  String _timestamp(Duration value) {
    final totalMinutes = value.inMinutes;
    final seconds = value.inSeconds.remainder(60);
    final centiseconds = (value.inMilliseconds.remainder(1000) / 10).floor();
    return '[${totalMinutes.toString().padLeft(2, '0')}:'
        '${seconds.toString().padLeft(2, '0')}.'
        '${centiseconds.toString().padLeft(2, '0')}]';
  }
}
